version: '3'

services:
   db:
     image: mysql:5.7
     container_name: mysql
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
     env_file: ./../.env
     environment:
       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
       - MYSQL_DATABASE=default
       - MYSQL_USER=${MYSQL_USER}
       - MYSQL_PASSWORD=${MYSQL_PASS}
     ports: 
       - '3306:3306'
volumes:
    dbdata:
